version: 0.0
os: linux
files:
  - source: /
    destination: /mnt/code/html/
hooks:
  BeforeInstall:
    - location: script/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root
